#!/usr/bin/env python3
"""Build a self-contained Kaggle kernel folder for the ROGII submission.

Optionally embeds a trained meta-learner pickle (``--meta-model``) which
the kernel will base64-decode and pass to ``make_submission`` when the
model kind is ``meta_pf``.
"""

from __future__ import annotations

import argparse
import base64
import json
from pathlib import Path
import textwrap
import zipfile


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = Path("/private/tmp/rogii_kaggle_kernel")
PACKAGE_DIR = ROOT / "src" / "rogii_baseline"


def _zip_package() -> str:
    archive_path = DEFAULT_OUTPUT / "rogii_baseline_src.zip"
    archive_path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(archive_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(PACKAGE_DIR.glob("*.py")):
            archive.write(path, Path("rogii_baseline") / path.name)
    payload = archive_path.read_bytes()
    archive_path.unlink()
    return base64.b64encode(payload).decode("ascii")


def _script(package_zip_b64: str, meta_model_b64: str | None, default_model_kind: str) -> str:
    meta_section = (
        f"META_MODEL_B64 = {meta_model_b64!r}\n"
        if meta_model_b64 is not None
        else "META_MODEL_B64 = None\n"
    )
    return textwrap.dedent(
        f"""
        # %% [markdown]
        # # ROGII Wellbore Geology Prediction Baseline
        #
        # Self-contained Kaggle script generated by scripts/build_kaggle_kernel.py.

        # %%
        from pathlib import Path
        import base64
        import os
        import pickle
        import sys
        import zipfile

        PACKAGE_ZIP_B64 = {package_zip_b64!r}
        {meta_section}
        def _bootstrap_package() -> None:
            target = Path("/kaggle/working/src")
            package = target / "rogii_baseline"
            if package.exists():
                sys.path.insert(0, str(target))
                return
            target.mkdir(parents=True, exist_ok=True)
            archive_path = Path("/kaggle/working/rogii_baseline_src.zip")
            archive_path.write_bytes(base64.b64decode(PACKAGE_ZIP_B64))
            with zipfile.ZipFile(archive_path) as archive:
                archive.extractall(target)
            sys.path.insert(0, str(target))

        _bootstrap_package()

        os.environ.setdefault("ROGII_DATA_DIR", "/kaggle/input/rogii-wellbore-geology-prediction")
        os.environ.setdefault("ROGII_PF_N_SEEDS", "128")
        os.environ.setdefault("ROGII_PF_N_PARTICLES", "500")
        os.environ.setdefault("ROGII_MODEL_KIND", {default_model_kind!r})

        from rogii_baseline.baseline import make_submission

        meta_payload = None
        if META_MODEL_B64 is not None:
            meta_payload = pickle.loads(base64.b64decode(META_MODEL_B64))

        # %%
        submission = make_submission(
            data_dir=os.environ["ROGII_DATA_DIR"],
            output_path="/kaggle/working/submission.csv",
            model_kind=os.environ.get("ROGII_MODEL_KIND", {default_model_kind!r}),
            max_train_rows=int(os.environ.get("ROGII_MAX_TRAIN_ROWS", "800000")),
            pf_n_particles=int(os.environ.get("ROGII_PF_N_PARTICLES", "500")),
            pf_n_seeds=int(os.environ.get("ROGII_PF_N_SEEDS", "128")),
            pf_likelihood_scale=float(os.environ.get("ROGII_PF_LIKELIHOOD_SCALE", "5.0")),
            physical_blend_weight=float(os.environ.get("ROGII_PHYSICAL_BLEND_WEIGHT", "0.75")),
            pf_blend_weight=float(os.environ.get("ROGII_PF_BLEND_WEIGHT", "0.125")),
            beam_blend_weight=float(os.environ.get("ROGII_BEAM_BLEND_WEIGHT", "0.125")),
            meta_model_payload=meta_payload,
        )
        submission.head()
        """
    ).lstrip()


def build(output_dir: Path, kernel_id: str, meta_model_path: Path | None, default_model_kind: str) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    meta_b64: str | None = None
    if meta_model_path is not None:
        meta_b64 = base64.b64encode(meta_model_path.read_bytes()).decode("ascii")
    script_path = output_dir / "rogii_baseline_submission.py"
    script_path.write_text(_script(_zip_package(), meta_b64, default_model_kind), encoding="utf-8")
    metadata = {
        "id": kernel_id,
        "title": "ROGII Baseline Submission",
        "code_file": script_path.name,
        "language": "python",
        "kernel_type": "script",
        "is_private": True,
        "enable_gpu": False,
        "enable_internet": False,
        "competition_sources": ["rogii-wellbore-geology-prediction"],
        "dataset_sources": [],
        "kernel_sources": [],
    }
    (output_dir / "kernel-metadata.json").write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Build a self-contained Kaggle kernel folder.")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--kernel-id", default="josephmontana/rogii-baseline-submission")
    parser.add_argument("--meta-model", type=Path, default=None, help="Path to a trained meta-learner pickle to embed.")
    parser.add_argument("--model-kind", default="formation_pf", help="Default model_kind for the kernel.")
    args = parser.parse_args()
    build(args.output_dir, args.kernel_id, args.meta_model, args.model_kind)
    print(f"Wrote Kaggle kernel folder to {args.output_dir}")


if __name__ == "__main__":
    main()
